import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styled, { keyframes } from 'styled-components';
import Button from '../src/components/atoms/Button';
import { headingOne, primaryLight, secondaryLight } from '../src/theme';

const GradientAnimation = keyframes`
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
`

const Container = styled.div`
  min-height: 100vh;
  padding: 0 0.5rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background: linear-gradient(300deg,${primaryLight},${secondaryLight},${primaryLight});
  background-size: 180% 180%;
  animation: ${GradientAnimation} 18s ease infinite;
`

const Main = styled.main`
  padding: 5rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

const Footer = styled.footer`
  width: 100%;
  height: 100px;
  border-top: 1px solid #eaeaea;
  display: flex;
  justify-content: center;
  align-items: center;

  a {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-grow: 1;
  }
`

const Title = styled.h1`
  font-family: ${headingOne.fontFamily};
  font-size: ${headingOne.fontSize.desktop};
  font-weight: ${headingOne.fontWeight};
  color: ${headingOne.color};
`

const Logo = styled.span`
  height: 1em;
  margin-left: 0.5rem;
`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />
        <link href="https://fonts.googleapis.com/css2?family=Sofia&display=swap" rel="stylesheet" />
      </Head>

      <Main>
        <Title>
          Clairvoyage
        </Title>
        <Button text='Submit' />
      </Main>
      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <Logo>
            <Image src="/chat.svg" alt="Chat Icon" width={32} height={32} />>
          </Logo>
        </a>
      </Footer>
    </Container>
  )
}

export default Home
