import type { NextPage } from 'next'
import Head from 'next/head'
import PageLayout from '../src/components/templates/PageLayout';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />
        <link href="https://fonts.googleapis.com/css2?family=Sofia&display=swap" rel="stylesheet" />
      </Head>
      <PageLayout 
        leftSidebar={
          <div>Hello from Left Sidebar</div>
        }
        mainContent={<div>Hello World</div>}
        rightSidebar={
          <div>Hello from Right Sidebar</div>
        }
      />
    </>
  )
}

export default Home
